[package]
name = "rust"
version = "0.1.0"
authors = ["Ussama Azam <nuclearoreo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3"
regex = "0.2"
reqwest = "0.8.3"
